default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= Figaro.env.database_pool %>
  timeout: 50000
  host: <%= Figaro.env.database_host %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>

development:
  <<: *default
  database: <%= Figaro.env.database_name %>

test: &test
  <<: *default
  database: dana_parking_test

production:
  <<: *default
  database: <%= Figaro.env.database_name %>
